name: James Reilly
favicon: null
layout_spectrum: 0.31117589212954044
typography_spectrum: 0.75191
title: Home of Digital Designer James Reilly
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8176570448558778
  lightness: 0.8109627882950008
  saturation: 0.8792639037128538
  rhythmicContrast: 0.8929702450986952
purpose: []
